// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetPreferences implements getPreferences operation.
	//
	// GET /v1/recipients/{recipient_id}/preferences
	GetPreferences(ctx context.Context, params GetPreferencesParams) (*Preferences, error)
	// IssueKey implements issueKey operation.
	//
	// POST /admin/projects/{project_id}/keys
	IssueKey(ctx context.Context, req *APIKeyRequest, params IssueKeyParams) (*IssuedKey, error)
	// ListDeadLetters implements listDeadLetters operation.
	//
	// GET /admin/projects/{project_id}/dead-letters
	ListDeadLetters(ctx context.Context, params ListDeadLettersParams) (*DeadLetters, error)
	// ListKeys implements listKeys operation.
	//
	// GET /admin/projects/{project_id}/keys
	ListKeys(ctx context.Context, params ListKeysParams) (*APIKeys, error)
	// ListProjects implements listProjects operation.
	//
	// GET /admin/projects
	ListProjects(ctx context.Context) (*Projects, error)
	// ListProviders implements listProviders operation.
	//
	// GET /admin/projects/{project_id}/providers
	ListProviders(ctx context.Context, params ListProvidersParams) (*Providers, error)
	// Login implements login operation.
	//
	// POST /admin/session
	Login(ctx context.Context, req *LoginRequest) error
	// Logout implements logout operation.
	//
	// DELETE /admin/session
	Logout(ctx context.Context) error
	// Preview implements preview operation.
	//
	// POST /admin/projects/{project_id}/preview
	Preview(ctx context.Context, req *PreviewRequest, params PreviewParams) (*Rendered, error)
	// PutPreferences implements putPreferences operation.
	//
	// PUT /v1/recipients/{recipient_id}/preferences
	PutPreferences(ctx context.Context, req *Preferences, params PutPreferencesParams) error
	// PutProject implements putProject operation.
	//
	// PUT /admin/projects/{project_id}
	PutProject(ctx context.Context, req *ProjectConfig, params PutProjectParams) error
	// PutProvider implements putProvider operation.
	//
	// PUT /admin/projects/{project_id}/providers
	PutProvider(ctx context.Context, req *ProviderSettings, params PutProviderParams) error
	// Replay implements replay operation.
	//
	// POST /admin/projects/{project_id}/dead-letters/{delivery_id}/replay
	Replay(ctx context.Context, params ReplayParams) error
	// RevokeKey implements revokeKey operation.
	//
	// DELETE /admin/projects/{project_id}/keys/{key_id}
	RevokeKey(ctx context.Context, params RevokeKeyParams) error
	// Send implements send operation.
	//
	// POST /v1/messages
	Send(ctx context.Context, req *SendRequest) (*Accepted, error)
	// TestSend implements testSend operation.
	//
	// POST /admin/projects/{project_id}/test
	TestSend(ctx context.Context, req *SendRequest, params TestSendParams) (*Accepted, error)
	// NewError creates *ProblemStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ProblemStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
