// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/google/uuid"
)

func (s *ProblemStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/APIKey
type APIKey struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

// GetID returns the value of ID.
func (s *APIKey) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *APIKey) GetName() string {
	return s.Name
}

// GetCreatedAt returns the value of CreatedAt.
func (s *APIKey) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *APIKey) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *APIKey) SetName(val string) {
	s.Name = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *APIKey) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// Ref: #/components/schemas/APIKeyRequest
type APIKeyRequest struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *APIKeyRequest) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *APIKeyRequest) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/APIKeys
type APIKeys struct {
	Items []APIKey `json:"items"`
}

// GetItems returns the value of Items.
func (s *APIKeys) GetItems() []APIKey {
	return s.Items
}

// SetItems sets the value of Items.
func (s *APIKeys) SetItems(val []APIKey) {
	s.Items = val
}

// Ref: #/components/schemas/Accepted
type Accepted struct {
	MessageID      uuid.UUID        `json:"message_id"`
	Accepted       AcceptedAccepted `json:"accepted"`
	QueuedChannels []Channel        `json:"queued_channels"`
}

// GetMessageID returns the value of MessageID.
func (s *Accepted) GetMessageID() uuid.UUID {
	return s.MessageID
}

// GetAccepted returns the value of Accepted.
func (s *Accepted) GetAccepted() AcceptedAccepted {
	return s.Accepted
}

// GetQueuedChannels returns the value of QueuedChannels.
func (s *Accepted) GetQueuedChannels() []Channel {
	return s.QueuedChannels
}

// SetMessageID sets the value of MessageID.
func (s *Accepted) SetMessageID(val uuid.UUID) {
	s.MessageID = val
}

// SetAccepted sets the value of Accepted.
func (s *Accepted) SetAccepted(val AcceptedAccepted) {
	s.Accepted = val
}

// SetQueuedChannels sets the value of QueuedChannels.
func (s *Accepted) SetQueuedChannels(val []Channel) {
	s.QueuedChannels = val
}

type AcceptedAccepted bool

const (
	AcceptedAcceptedTrue AcceptedAccepted = true
)

// AllValues returns all AcceptedAccepted values.
func (AcceptedAccepted) AllValues() []AcceptedAccepted {
	return []AcceptedAccepted{
		AcceptedAcceptedTrue,
	}
}

type AdminSession struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *AdminSession) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *AdminSession) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *AdminSession) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *AdminSession) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/Channel
type Channel string

const (
	ChannelEmail   Channel = "email"
	ChannelWebpush Channel = "webpush"
	ChannelFcm     Channel = "fcm"
)

// AllValues returns all Channel values.
func (Channel) AllValues() []Channel {
	return []Channel{
		ChannelEmail,
		ChannelWebpush,
		ChannelFcm,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Channel) MarshalText() ([]byte, error) {
	switch s {
	case ChannelEmail:
		return []byte(s), nil
	case ChannelWebpush:
		return []byte(s), nil
	case ChannelFcm:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Channel) UnmarshalText(data []byte) error {
	switch Channel(data) {
	case ChannelEmail:
		*s = ChannelEmail
		return nil
	case ChannelWebpush:
		*s = ChannelWebpush
		return nil
	case ChannelFcm:
		*s = ChannelFcm
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChannelConfig
type ChannelConfig struct {
	Channel   Channel                `json:"channel"`
	Schema    Schema                 `json:"schema"`
	Labels    OptChannelConfigLabels `json:"labels"`
	Templates []Template             `json:"templates"`
}

// GetChannel returns the value of Channel.
func (s *ChannelConfig) GetChannel() Channel {
	return s.Channel
}

// GetSchema returns the value of Schema.
func (s *ChannelConfig) GetSchema() Schema {
	return s.Schema
}

// GetLabels returns the value of Labels.
func (s *ChannelConfig) GetLabels() OptChannelConfigLabels {
	return s.Labels
}

// GetTemplates returns the value of Templates.
func (s *ChannelConfig) GetTemplates() []Template {
	return s.Templates
}

// SetChannel sets the value of Channel.
func (s *ChannelConfig) SetChannel(val Channel) {
	s.Channel = val
}

// SetSchema sets the value of Schema.
func (s *ChannelConfig) SetSchema(val Schema) {
	s.Schema = val
}

// SetLabels sets the value of Labels.
func (s *ChannelConfig) SetLabels(val OptChannelConfigLabels) {
	s.Labels = val
}

// SetTemplates sets the value of Templates.
func (s *ChannelConfig) SetTemplates(val []Template) {
	s.Templates = val
}

type ChannelConfigLabels map[string]Translations

func (s *ChannelConfigLabels) init() ChannelConfigLabels {
	m := *s
	if m == nil {
		m = map[string]Translations{}
		*s = m
	}
	return m
}

// Dynamic JSON object validated against the configured schemapb schema.
// Ref: #/components/schemas/Data
type Data map[string]jx.Raw

func (s *Data) init() Data {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/DeadLetter
type DeadLetter struct {
	ID         uuid.UUID `json:"id"`
	Attempts   int       `json:"attempts"`
	ErrorCode  string    `json:"error_code"`
	FinishedAt time.Time `json:"finished_at"`
	Snapshot   Snapshot  `json:"snapshot"`
}

// GetID returns the value of ID.
func (s *DeadLetter) GetID() uuid.UUID {
	return s.ID
}

// GetAttempts returns the value of Attempts.
func (s *DeadLetter) GetAttempts() int {
	return s.Attempts
}

// GetErrorCode returns the value of ErrorCode.
func (s *DeadLetter) GetErrorCode() string {
	return s.ErrorCode
}

// GetFinishedAt returns the value of FinishedAt.
func (s *DeadLetter) GetFinishedAt() time.Time {
	return s.FinishedAt
}

// GetSnapshot returns the value of Snapshot.
func (s *DeadLetter) GetSnapshot() Snapshot {
	return s.Snapshot
}

// SetID sets the value of ID.
func (s *DeadLetter) SetID(val uuid.UUID) {
	s.ID = val
}

// SetAttempts sets the value of Attempts.
func (s *DeadLetter) SetAttempts(val int) {
	s.Attempts = val
}

// SetErrorCode sets the value of ErrorCode.
func (s *DeadLetter) SetErrorCode(val string) {
	s.ErrorCode = val
}

// SetFinishedAt sets the value of FinishedAt.
func (s *DeadLetter) SetFinishedAt(val time.Time) {
	s.FinishedAt = val
}

// SetSnapshot sets the value of Snapshot.
func (s *DeadLetter) SetSnapshot(val Snapshot) {
	s.Snapshot = val
}

// Up to 100 oldest dead letters; use after cursor for subsequent pages.
// Ref: #/components/schemas/DeadLetters
type DeadLetters struct {
	Items []DeadLetter `json:"items"`
}

// GetItems returns the value of Items.
func (s *DeadLetters) GetItems() []DeadLetter {
	return s.Items
}

// SetItems sets the value of Items.
func (s *DeadLetters) SetItems(val []DeadLetter) {
	s.Items = val
}

// Exactly one target matching channel is required. At most one delivery per channel.
// Ref: #/components/schemas/DeliveryInput
type DeliveryInput struct {
	Channel        Channel          `json:"channel"`
	DefaultEnabled bool             `json:"default_enabled"`
	Data           Data             `json:"data"`
	Email          OptEmailTarget   `json:"email"`
	Webpush        OptWebPushTarget `json:"webpush"`
	Fcm            OptFCMTarget     `json:"fcm"`
}

// GetChannel returns the value of Channel.
func (s *DeliveryInput) GetChannel() Channel {
	return s.Channel
}

// GetDefaultEnabled returns the value of DefaultEnabled.
func (s *DeliveryInput) GetDefaultEnabled() bool {
	return s.DefaultEnabled
}

// GetData returns the value of Data.
func (s *DeliveryInput) GetData() Data {
	return s.Data
}

// GetEmail returns the value of Email.
func (s *DeliveryInput) GetEmail() OptEmailTarget {
	return s.Email
}

// GetWebpush returns the value of Webpush.
func (s *DeliveryInput) GetWebpush() OptWebPushTarget {
	return s.Webpush
}

// GetFcm returns the value of Fcm.
func (s *DeliveryInput) GetFcm() OptFCMTarget {
	return s.Fcm
}

// SetChannel sets the value of Channel.
func (s *DeliveryInput) SetChannel(val Channel) {
	s.Channel = val
}

// SetDefaultEnabled sets the value of DefaultEnabled.
func (s *DeliveryInput) SetDefaultEnabled(val bool) {
	s.DefaultEnabled = val
}

// SetData sets the value of Data.
func (s *DeliveryInput) SetData(val Data) {
	s.Data = val
}

// SetEmail sets the value of Email.
func (s *DeliveryInput) SetEmail(val OptEmailTarget) {
	s.Email = val
}

// SetWebpush sets the value of Webpush.
func (s *DeliveryInput) SetWebpush(val OptWebPushTarget) {
	s.Webpush = val
}

// SetFcm sets the value of Fcm.
func (s *DeliveryInput) SetFcm(val OptFCMTarget) {
	s.Fcm = val
}

// Ref: #/components/schemas/EmailTarget
type EmailTarget struct {
	Address string `json:"address"`
}

// GetAddress returns the value of Address.
func (s *EmailTarget) GetAddress() string {
	return s.Address
}

// SetAddress sets the value of Address.
func (s *EmailTarget) SetAddress(val string) {
	s.Address = val
}

// Ref: #/components/schemas/FCMSettings
type FCMSettings struct {
	ProjectID      string `json:"project_id"`
	ServiceAccount Data   `json:"service_account"`
}

// GetProjectID returns the value of ProjectID.
func (s *FCMSettings) GetProjectID() string {
	return s.ProjectID
}

// GetServiceAccount returns the value of ServiceAccount.
func (s *FCMSettings) GetServiceAccount() Data {
	return s.ServiceAccount
}

// SetProjectID sets the value of ProjectID.
func (s *FCMSettings) SetProjectID(val string) {
	s.ProjectID = val
}

// SetServiceAccount sets the value of ServiceAccount.
func (s *FCMSettings) SetServiceAccount(val Data) {
	s.ServiceAccount = val
}

// Ref: #/components/schemas/FCMTarget
type FCMTarget struct {
	Token string `json:"token"`
}

// GetToken returns the value of Token.
func (s *FCMTarget) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *FCMTarget) SetToken(val string) {
	s.Token = val
}

// Secret is shown once.
// Ref: #/components/schemas/IssuedKey
type IssuedKey struct {
	ID     uuid.UUID `json:"id"`
	Secret string    `json:"secret"`
}

// GetID returns the value of ID.
func (s *IssuedKey) GetID() uuid.UUID {
	return s.ID
}

// GetSecret returns the value of Secret.
func (s *IssuedKey) GetSecret() string {
	return s.Secret
}

// SetID sets the value of ID.
func (s *IssuedKey) SetID(val uuid.UUID) {
	s.ID = val
}

// SetSecret sets the value of Secret.
func (s *IssuedKey) SetSecret(val string) {
	s.Secret = val
}

// LoginNoContent is response for Login operation.
type LoginNoContent struct{}

// Ref: #/components/schemas/LoginRequest
type LoginRequest struct {
	Key string `json:"key"`
}

// GetKey returns the value of Key.
func (s *LoginRequest) GetKey() string {
	return s.Key
}

// SetKey sets the value of Key.
func (s *LoginRequest) SetKey(val string) {
	s.Key = val
}

// LogoutNoContent is response for Logout operation.
type LogoutNoContent struct{}

// Ref: #/components/schemas/Notification
type Notification struct {
	Key         string          `json:"key"`
	Active      bool            `json:"active"`
	Title       Translations    `json:"title"`
	Description Translations    `json:"description"`
	Channels    []ChannelConfig `json:"channels"`
}

// GetKey returns the value of Key.
func (s *Notification) GetKey() string {
	return s.Key
}

// GetActive returns the value of Active.
func (s *Notification) GetActive() bool {
	return s.Active
}

// GetTitle returns the value of Title.
func (s *Notification) GetTitle() Translations {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *Notification) GetDescription() Translations {
	return s.Description
}

// GetChannels returns the value of Channels.
func (s *Notification) GetChannels() []ChannelConfig {
	return s.Channels
}

// SetKey sets the value of Key.
func (s *Notification) SetKey(val string) {
	s.Key = val
}

// SetActive sets the value of Active.
func (s *Notification) SetActive(val bool) {
	s.Active = val
}

// SetTitle sets the value of Title.
func (s *Notification) SetTitle(val Translations) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *Notification) SetDescription(val Translations) {
	s.Description = val
}

// SetChannels sets the value of Channels.
func (s *Notification) SetChannels(val []ChannelConfig) {
	s.Channels = val
}

// NewOptChannelConfigLabels returns new OptChannelConfigLabels with value set to v.
func NewOptChannelConfigLabels(v ChannelConfigLabels) OptChannelConfigLabels {
	return OptChannelConfigLabels{
		Value: v,
		Set:   true,
	}
}

// OptChannelConfigLabels is optional ChannelConfigLabels.
type OptChannelConfigLabels struct {
	Value ChannelConfigLabels
	Set   bool
}

// IsSet returns true if OptChannelConfigLabels was set.
func (o OptChannelConfigLabels) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptChannelConfigLabels) Reset() {
	var v ChannelConfigLabels
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptChannelConfigLabels) SetTo(v ChannelConfigLabels) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptChannelConfigLabels) Get() (v ChannelConfigLabels, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptChannelConfigLabels) Or(d ChannelConfigLabels) ChannelConfigLabels {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptEmailTarget returns new OptEmailTarget with value set to v.
func NewOptEmailTarget(v EmailTarget) OptEmailTarget {
	return OptEmailTarget{
		Value: v,
		Set:   true,
	}
}

// OptEmailTarget is optional EmailTarget.
type OptEmailTarget struct {
	Value EmailTarget
	Set   bool
}

// IsSet returns true if OptEmailTarget was set.
func (o OptEmailTarget) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEmailTarget) Reset() {
	var v EmailTarget
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEmailTarget) SetTo(v EmailTarget) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEmailTarget) Get() (v EmailTarget, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEmailTarget) Or(d EmailTarget) EmailTarget {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFCMSettings returns new OptFCMSettings with value set to v.
func NewOptFCMSettings(v FCMSettings) OptFCMSettings {
	return OptFCMSettings{
		Value: v,
		Set:   true,
	}
}

// OptFCMSettings is optional FCMSettings.
type OptFCMSettings struct {
	Value FCMSettings
	Set   bool
}

// IsSet returns true if OptFCMSettings was set.
func (o OptFCMSettings) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFCMSettings) Reset() {
	var v FCMSettings
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFCMSettings) SetTo(v FCMSettings) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFCMSettings) Get() (v FCMSettings, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFCMSettings) Or(d FCMSettings) FCMSettings {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFCMTarget returns new OptFCMTarget with value set to v.
func NewOptFCMTarget(v FCMTarget) OptFCMTarget {
	return OptFCMTarget{
		Value: v,
		Set:   true,
	}
}

// OptFCMTarget is optional FCMTarget.
type OptFCMTarget struct {
	Value FCMTarget
	Set   bool
}

// IsSet returns true if OptFCMTarget was set.
func (o OptFCMTarget) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFCMTarget) Reset() {
	var v FCMTarget
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFCMTarget) SetTo(v FCMTarget) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFCMTarget) Get() (v FCMTarget, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFCMTarget) Or(d FCMTarget) FCMTarget {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSMTPSettings returns new OptSMTPSettings with value set to v.
func NewOptSMTPSettings(v SMTPSettings) OptSMTPSettings {
	return OptSMTPSettings{
		Value: v,
		Set:   true,
	}
}

// OptSMTPSettings is optional SMTPSettings.
type OptSMTPSettings struct {
	Value SMTPSettings
	Set   bool
}

// IsSet returns true if OptSMTPSettings was set.
func (o OptSMTPSettings) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSMTPSettings) Reset() {
	var v SMTPSettings
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSMTPSettings) SetTo(v SMTPSettings) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSMTPSettings) Get() (v SMTPSettings, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSMTPSettings) Or(d SMTPSettings) SMTPSettings {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptWebPushSettings returns new OptWebPushSettings with value set to v.
func NewOptWebPushSettings(v WebPushSettings) OptWebPushSettings {
	return OptWebPushSettings{
		Value: v,
		Set:   true,
	}
}

// OptWebPushSettings is optional WebPushSettings.
type OptWebPushSettings struct {
	Value WebPushSettings
	Set   bool
}

// IsSet returns true if OptWebPushSettings was set.
func (o OptWebPushSettings) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptWebPushSettings) Reset() {
	var v WebPushSettings
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptWebPushSettings) SetTo(v WebPushSettings) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptWebPushSettings) Get() (v WebPushSettings, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptWebPushSettings) Or(d WebPushSettings) WebPushSettings {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptWebPushTarget returns new OptWebPushTarget with value set to v.
func NewOptWebPushTarget(v WebPushTarget) OptWebPushTarget {
	return OptWebPushTarget{
		Value: v,
		Set:   true,
	}
}

// OptWebPushTarget is optional WebPushTarget.
type OptWebPushTarget struct {
	Value WebPushTarget
	Set   bool
}

// IsSet returns true if OptWebPushTarget was set.
func (o OptWebPushTarget) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptWebPushTarget) Reset() {
	var v WebPushTarget
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptWebPushTarget) SetTo(v WebPushTarget) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptWebPushTarget) Get() (v WebPushTarget, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptWebPushTarget) Or(d WebPushTarget) WebPushTarget {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Preference
type Preference struct {
	NotificationKey string  `json:"notification_key"`
	Channel         Channel `json:"channel"`
	Enabled         bool    `json:"enabled"`
}

// GetNotificationKey returns the value of NotificationKey.
func (s *Preference) GetNotificationKey() string {
	return s.NotificationKey
}

// GetChannel returns the value of Channel.
func (s *Preference) GetChannel() Channel {
	return s.Channel
}

// GetEnabled returns the value of Enabled.
func (s *Preference) GetEnabled() bool {
	return s.Enabled
}

// SetNotificationKey sets the value of NotificationKey.
func (s *Preference) SetNotificationKey(val string) {
	s.NotificationKey = val
}

// SetChannel sets the value of Channel.
func (s *Preference) SetChannel(val Channel) {
	s.Channel = val
}

// SetEnabled sets the value of Enabled.
func (s *Preference) SetEnabled(val bool) {
	s.Enabled = val
}

// Ref: #/components/schemas/Preferences
type Preferences struct {
	Rules []Preference `json:"rules"`
}

// GetRules returns the value of Rules.
func (s *Preferences) GetRules() []Preference {
	return s.Rules
}

// SetRules sets the value of Rules.
func (s *Preferences) SetRules(val []Preference) {
	s.Rules = val
}

// Ref: #/components/schemas/PreviewRequest
type PreviewRequest struct {
	NotificationKey string    `json:"notification_key"`
	Channel         Channel   `json:"channel"`
	Locale          OptString `json:"locale"`
	Data            Data      `json:"data"`
}

// GetNotificationKey returns the value of NotificationKey.
func (s *PreviewRequest) GetNotificationKey() string {
	return s.NotificationKey
}

// GetChannel returns the value of Channel.
func (s *PreviewRequest) GetChannel() Channel {
	return s.Channel
}

// GetLocale returns the value of Locale.
func (s *PreviewRequest) GetLocale() OptString {
	return s.Locale
}

// GetData returns the value of Data.
func (s *PreviewRequest) GetData() Data {
	return s.Data
}

// SetNotificationKey sets the value of NotificationKey.
func (s *PreviewRequest) SetNotificationKey(val string) {
	s.NotificationKey = val
}

// SetChannel sets the value of Channel.
func (s *PreviewRequest) SetChannel(val Channel) {
	s.Channel = val
}

// SetLocale sets the value of Locale.
func (s *PreviewRequest) SetLocale(val OptString) {
	s.Locale = val
}

// SetData sets the value of Data.
func (s *PreviewRequest) SetData(val Data) {
	s.Data = val
}

// Ref: #/components/schemas/Problem
type Problem struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Problem) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Problem) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Problem) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Problem) SetMessage(val string) {
	s.Message = val
}

// ProblemStatusCode wraps Problem with StatusCode.
type ProblemStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ProblemStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ProblemStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ProblemStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ProblemStatusCode) SetResponse(val Problem) {
	s.Response = val
}

// Ref: #/components/schemas/Project
type Project struct {
	ID     string        `json:"id"`
	Config ProjectConfig `json:"config"`
}

// GetID returns the value of ID.
func (s *Project) GetID() string {
	return s.ID
}

// GetConfig returns the value of Config.
func (s *Project) GetConfig() ProjectConfig {
	return s.Config
}

// SetID sets the value of ID.
func (s *Project) SetID(val string) {
	s.ID = val
}

// SetConfig sets the value of Config.
func (s *Project) SetConfig(val ProjectConfig) {
	s.Config = val
}

// Ref: #/components/schemas/ProjectConfig
type ProjectConfig struct {
	Title         Translations   `json:"title"`
	DefaultLocale string         `json:"default_locale"`
	Notifications []Notification `json:"notifications"`
}

// GetTitle returns the value of Title.
func (s *ProjectConfig) GetTitle() Translations {
	return s.Title
}

// GetDefaultLocale returns the value of DefaultLocale.
func (s *ProjectConfig) GetDefaultLocale() string {
	return s.DefaultLocale
}

// GetNotifications returns the value of Notifications.
func (s *ProjectConfig) GetNotifications() []Notification {
	return s.Notifications
}

// SetTitle sets the value of Title.
func (s *ProjectConfig) SetTitle(val Translations) {
	s.Title = val
}

// SetDefaultLocale sets the value of DefaultLocale.
func (s *ProjectConfig) SetDefaultLocale(val string) {
	s.DefaultLocale = val
}

// SetNotifications sets the value of Notifications.
func (s *ProjectConfig) SetNotifications(val []Notification) {
	s.Notifications = val
}

// Ref: #/components/schemas/Projects
type Projects struct {
	Items []Project `json:"items"`
}

// GetItems returns the value of Items.
func (s *Projects) GetItems() []Project {
	return s.Items
}

// SetItems sets the value of Items.
func (s *Projects) SetItems(val []Project) {
	s.Items = val
}

// Exactly one configuration matching channel; encrypted at rest and never returned by read APIs.
// Ref: #/components/schemas/ProviderSettings
type ProviderSettings struct {
	Channel Channel            `json:"channel"`
	SMTP    OptSMTPSettings    `json:"smtp"`
	Webpush OptWebPushSettings `json:"webpush"`
	Fcm     OptFCMSettings     `json:"fcm"`
}

// GetChannel returns the value of Channel.
func (s *ProviderSettings) GetChannel() Channel {
	return s.Channel
}

// GetSMTP returns the value of SMTP.
func (s *ProviderSettings) GetSMTP() OptSMTPSettings {
	return s.SMTP
}

// GetWebpush returns the value of Webpush.
func (s *ProviderSettings) GetWebpush() OptWebPushSettings {
	return s.Webpush
}

// GetFcm returns the value of Fcm.
func (s *ProviderSettings) GetFcm() OptFCMSettings {
	return s.Fcm
}

// SetChannel sets the value of Channel.
func (s *ProviderSettings) SetChannel(val Channel) {
	s.Channel = val
}

// SetSMTP sets the value of SMTP.
func (s *ProviderSettings) SetSMTP(val OptSMTPSettings) {
	s.SMTP = val
}

// SetWebpush sets the value of Webpush.
func (s *ProviderSettings) SetWebpush(val OptWebPushSettings) {
	s.Webpush = val
}

// SetFcm sets the value of Fcm.
func (s *ProviderSettings) SetFcm(val OptFCMSettings) {
	s.Fcm = val
}

// Ref: #/components/schemas/ProviderStatus
type ProviderStatus struct {
	Channel    Channel `json:"channel"`
	Configured bool    `json:"configured"`
}

// GetChannel returns the value of Channel.
func (s *ProviderStatus) GetChannel() Channel {
	return s.Channel
}

// GetConfigured returns the value of Configured.
func (s *ProviderStatus) GetConfigured() bool {
	return s.Configured
}

// SetChannel sets the value of Channel.
func (s *ProviderStatus) SetChannel(val Channel) {
	s.Channel = val
}

// SetConfigured sets the value of Configured.
func (s *ProviderStatus) SetConfigured(val bool) {
	s.Configured = val
}

// Ref: #/components/schemas/Providers
type Providers struct {
	Items []ProviderStatus `json:"items"`
}

// GetItems returns the value of Items.
func (s *Providers) GetItems() []ProviderStatus {
	return s.Items
}

// SetItems sets the value of Items.
func (s *Providers) SetItems(val []ProviderStatus) {
	s.Items = val
}

// PutPreferencesNoContent is response for PutPreferences operation.
type PutPreferencesNoContent struct{}

// PutProjectNoContent is response for PutProject operation.
type PutProjectNoContent struct{}

// PutProviderNoContent is response for PutProvider operation.
type PutProviderNoContent struct{}

// Ref: #/components/schemas/Rendered
type Rendered struct {
	Locale  string `json:"locale"`
	Subject string `json:"subject"`
	Text    string `json:"text"`
	HTML    string `json:"html"`
	ReplyTo string `json:"reply_to"`
	Title   string `json:"title"`
	Body    string `json:"body"`
	URL     string `json:"url"`
}

// GetLocale returns the value of Locale.
func (s *Rendered) GetLocale() string {
	return s.Locale
}

// GetSubject returns the value of Subject.
func (s *Rendered) GetSubject() string {
	return s.Subject
}

// GetText returns the value of Text.
func (s *Rendered) GetText() string {
	return s.Text
}

// GetHTML returns the value of HTML.
func (s *Rendered) GetHTML() string {
	return s.HTML
}

// GetReplyTo returns the value of ReplyTo.
func (s *Rendered) GetReplyTo() string {
	return s.ReplyTo
}

// GetTitle returns the value of Title.
func (s *Rendered) GetTitle() string {
	return s.Title
}

// GetBody returns the value of Body.
func (s *Rendered) GetBody() string {
	return s.Body
}

// GetURL returns the value of URL.
func (s *Rendered) GetURL() string {
	return s.URL
}

// SetLocale sets the value of Locale.
func (s *Rendered) SetLocale(val string) {
	s.Locale = val
}

// SetSubject sets the value of Subject.
func (s *Rendered) SetSubject(val string) {
	s.Subject = val
}

// SetText sets the value of Text.
func (s *Rendered) SetText(val string) {
	s.Text = val
}

// SetHTML sets the value of HTML.
func (s *Rendered) SetHTML(val string) {
	s.HTML = val
}

// SetReplyTo sets the value of ReplyTo.
func (s *Rendered) SetReplyTo(val string) {
	s.ReplyTo = val
}

// SetTitle sets the value of Title.
func (s *Rendered) SetTitle(val string) {
	s.Title = val
}

// SetBody sets the value of Body.
func (s *Rendered) SetBody(val string) {
	s.Body = val
}

// SetURL sets the value of URL.
func (s *Rendered) SetURL(val string) {
	s.URL = val
}

// ReplayNoContent is response for Replay operation.
type ReplayNoContent struct{}

// RevokeKeyNoContent is response for RevokeKey operation.
type RevokeKeyNoContent struct{}

// Plain is permitted only with the explicit development runtime flag.
// Ref: #/components/schemas/SMTPSettings
type SMTPSettings struct {
	Host     string          `json:"host"`
	Port     int             `json:"port"`
	TLS      SMTPSettingsTLS `json:"tls"`
	Username OptString       `json:"username"`
	Password OptString       `json:"password"`
	From     string          `json:"from"`
}

// GetHost returns the value of Host.
func (s *SMTPSettings) GetHost() string {
	return s.Host
}

// GetPort returns the value of Port.
func (s *SMTPSettings) GetPort() int {
	return s.Port
}

// GetTLS returns the value of TLS.
func (s *SMTPSettings) GetTLS() SMTPSettingsTLS {
	return s.TLS
}

// GetUsername returns the value of Username.
func (s *SMTPSettings) GetUsername() OptString {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *SMTPSettings) GetPassword() OptString {
	return s.Password
}

// GetFrom returns the value of From.
func (s *SMTPSettings) GetFrom() string {
	return s.From
}

// SetHost sets the value of Host.
func (s *SMTPSettings) SetHost(val string) {
	s.Host = val
}

// SetPort sets the value of Port.
func (s *SMTPSettings) SetPort(val int) {
	s.Port = val
}

// SetTLS sets the value of TLS.
func (s *SMTPSettings) SetTLS(val SMTPSettingsTLS) {
	s.TLS = val
}

// SetUsername sets the value of Username.
func (s *SMTPSettings) SetUsername(val OptString) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *SMTPSettings) SetPassword(val OptString) {
	s.Password = val
}

// SetFrom sets the value of From.
func (s *SMTPSettings) SetFrom(val string) {
	s.From = val
}

type SMTPSettingsTLS string

const (
	SMTPSettingsTLSStarttls SMTPSettingsTLS = "starttls"
	SMTPSettingsTLSTLS      SMTPSettingsTLS = "tls"
	SMTPSettingsTLSPlain    SMTPSettingsTLS = "plain"
)

// AllValues returns all SMTPSettingsTLS values.
func (SMTPSettingsTLS) AllValues() []SMTPSettingsTLS {
	return []SMTPSettingsTLS{
		SMTPSettingsTLSStarttls,
		SMTPSettingsTLSTLS,
		SMTPSettingsTLSPlain,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SMTPSettingsTLS) MarshalText() ([]byte, error) {
	switch s {
	case SMTPSettingsTLSStarttls:
		return []byte(s), nil
	case SMTPSettingsTLSTLS:
		return []byte(s), nil
	case SMTPSettingsTLSPlain:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SMTPSettingsTLS) UnmarshalText(data []byte) error {
	switch SMTPSettingsTLS(data) {
	case SMTPSettingsTLSStarttls:
		*s = SMTPSettingsTLSStarttls
		return nil
	case SMTPSettingsTLSTLS:
		*s = SMTPSettingsTLSTLS
		return nil
	case SMTPSettingsTLSPlain:
		*s = SMTPSettingsTLSPlain
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Schemapb Schema in protobuf JSON format. Strict objects only; computed fields, defaults, coercion
// and transformations are prohibited.
// Ref: #/components/schemas/Schema
type Schema map[string]jx.Raw

func (s *Schema) init() Schema {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/SendRequest
type SendRequest struct {
	NotificationKey string          `json:"notification_key"`
	IdempotencyKey  string          `json:"idempotency_key"`
	RecipientID     OptString       `json:"recipient_id"`
	Locale          OptString       `json:"locale"`
	ExpiresAt       OptDateTime     `json:"expires_at"`
	Deliveries      []DeliveryInput `json:"deliveries"`
}

// GetNotificationKey returns the value of NotificationKey.
func (s *SendRequest) GetNotificationKey() string {
	return s.NotificationKey
}

// GetIdempotencyKey returns the value of IdempotencyKey.
func (s *SendRequest) GetIdempotencyKey() string {
	return s.IdempotencyKey
}

// GetRecipientID returns the value of RecipientID.
func (s *SendRequest) GetRecipientID() OptString {
	return s.RecipientID
}

// GetLocale returns the value of Locale.
func (s *SendRequest) GetLocale() OptString {
	return s.Locale
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *SendRequest) GetExpiresAt() OptDateTime {
	return s.ExpiresAt
}

// GetDeliveries returns the value of Deliveries.
func (s *SendRequest) GetDeliveries() []DeliveryInput {
	return s.Deliveries
}

// SetNotificationKey sets the value of NotificationKey.
func (s *SendRequest) SetNotificationKey(val string) {
	s.NotificationKey = val
}

// SetIdempotencyKey sets the value of IdempotencyKey.
func (s *SendRequest) SetIdempotencyKey(val string) {
	s.IdempotencyKey = val
}

// SetRecipientID sets the value of RecipientID.
func (s *SendRequest) SetRecipientID(val OptString) {
	s.RecipientID = val
}

// SetLocale sets the value of Locale.
func (s *SendRequest) SetLocale(val OptString) {
	s.Locale = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *SendRequest) SetExpiresAt(val OptDateTime) {
	s.ExpiresAt = val
}

// SetDeliveries sets the value of Deliveries.
func (s *SendRequest) SetDeliveries(val []DeliveryInput) {
	s.Deliveries = val
}

type ServiceKey struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *ServiceKey) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *ServiceKey) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *ServiceKey) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *ServiceKey) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/Snapshot
type Snapshot struct {
	ProjectID       string           `json:"project_id"`
	MessageID       uuid.UUID        `json:"message_id"`
	NotificationKey string           `json:"notification_key"`
	RecipientID     string           `json:"recipient_id"`
	DefaultEnabled  bool             `json:"default_enabled"`
	Channel         Channel          `json:"channel"`
	Email           OptEmailTarget   `json:"email"`
	Webpush         OptWebPushTarget `json:"webpush"`
	Fcm             OptFCMTarget     `json:"fcm"`
	Rendered        Rendered         `json:"rendered"`
	ExpiresAt       OptDateTime      `json:"expires_at"`
	CreatedAt       time.Time        `json:"created_at"`
}

// GetProjectID returns the value of ProjectID.
func (s *Snapshot) GetProjectID() string {
	return s.ProjectID
}

// GetMessageID returns the value of MessageID.
func (s *Snapshot) GetMessageID() uuid.UUID {
	return s.MessageID
}

// GetNotificationKey returns the value of NotificationKey.
func (s *Snapshot) GetNotificationKey() string {
	return s.NotificationKey
}

// GetRecipientID returns the value of RecipientID.
func (s *Snapshot) GetRecipientID() string {
	return s.RecipientID
}

// GetDefaultEnabled returns the value of DefaultEnabled.
func (s *Snapshot) GetDefaultEnabled() bool {
	return s.DefaultEnabled
}

// GetChannel returns the value of Channel.
func (s *Snapshot) GetChannel() Channel {
	return s.Channel
}

// GetEmail returns the value of Email.
func (s *Snapshot) GetEmail() OptEmailTarget {
	return s.Email
}

// GetWebpush returns the value of Webpush.
func (s *Snapshot) GetWebpush() OptWebPushTarget {
	return s.Webpush
}

// GetFcm returns the value of Fcm.
func (s *Snapshot) GetFcm() OptFCMTarget {
	return s.Fcm
}

// GetRendered returns the value of Rendered.
func (s *Snapshot) GetRendered() Rendered {
	return s.Rendered
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *Snapshot) GetExpiresAt() OptDateTime {
	return s.ExpiresAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Snapshot) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetProjectID sets the value of ProjectID.
func (s *Snapshot) SetProjectID(val string) {
	s.ProjectID = val
}

// SetMessageID sets the value of MessageID.
func (s *Snapshot) SetMessageID(val uuid.UUID) {
	s.MessageID = val
}

// SetNotificationKey sets the value of NotificationKey.
func (s *Snapshot) SetNotificationKey(val string) {
	s.NotificationKey = val
}

// SetRecipientID sets the value of RecipientID.
func (s *Snapshot) SetRecipientID(val string) {
	s.RecipientID = val
}

// SetDefaultEnabled sets the value of DefaultEnabled.
func (s *Snapshot) SetDefaultEnabled(val bool) {
	s.DefaultEnabled = val
}

// SetChannel sets the value of Channel.
func (s *Snapshot) SetChannel(val Channel) {
	s.Channel = val
}

// SetEmail sets the value of Email.
func (s *Snapshot) SetEmail(val OptEmailTarget) {
	s.Email = val
}

// SetWebpush sets the value of Webpush.
func (s *Snapshot) SetWebpush(val OptWebPushTarget) {
	s.Webpush = val
}

// SetFcm sets the value of Fcm.
func (s *Snapshot) SetFcm(val OptFCMTarget) {
	s.Fcm = val
}

// SetRendered sets the value of Rendered.
func (s *Snapshot) SetRendered(val Rendered) {
	s.Rendered = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *Snapshot) SetExpiresAt(val OptDateTime) {
	s.ExpiresAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Snapshot) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// Email requires subject and text or html; push requires title and body. URL must render to HTTPS
// when present.
// Ref: #/components/schemas/Template
type Template struct {
	Locale  string    `json:"locale"`
	Subject OptString `json:"subject"`
	Text    OptString `json:"text"`
	HTML    OptString `json:"html"`
	ReplyTo OptString `json:"reply_to"`
	Title   OptString `json:"title"`
	Body    OptString `json:"body"`
	URL     OptString `json:"url"`
}

// GetLocale returns the value of Locale.
func (s *Template) GetLocale() string {
	return s.Locale
}

// GetSubject returns the value of Subject.
func (s *Template) GetSubject() OptString {
	return s.Subject
}

// GetText returns the value of Text.
func (s *Template) GetText() OptString {
	return s.Text
}

// GetHTML returns the value of HTML.
func (s *Template) GetHTML() OptString {
	return s.HTML
}

// GetReplyTo returns the value of ReplyTo.
func (s *Template) GetReplyTo() OptString {
	return s.ReplyTo
}

// GetTitle returns the value of Title.
func (s *Template) GetTitle() OptString {
	return s.Title
}

// GetBody returns the value of Body.
func (s *Template) GetBody() OptString {
	return s.Body
}

// GetURL returns the value of URL.
func (s *Template) GetURL() OptString {
	return s.URL
}

// SetLocale sets the value of Locale.
func (s *Template) SetLocale(val string) {
	s.Locale = val
}

// SetSubject sets the value of Subject.
func (s *Template) SetSubject(val OptString) {
	s.Subject = val
}

// SetText sets the value of Text.
func (s *Template) SetText(val OptString) {
	s.Text = val
}

// SetHTML sets the value of HTML.
func (s *Template) SetHTML(val OptString) {
	s.HTML = val
}

// SetReplyTo sets the value of ReplyTo.
func (s *Template) SetReplyTo(val OptString) {
	s.ReplyTo = val
}

// SetTitle sets the value of Title.
func (s *Template) SetTitle(val OptString) {
	s.Title = val
}

// SetBody sets the value of Body.
func (s *Template) SetBody(val OptString) {
	s.Body = val
}

// SetURL sets the value of URL.
func (s *Template) SetURL(val OptString) {
	s.URL = val
}

// Ref: #/components/schemas/Translations
type Translations map[string]string

func (s *Translations) init() Translations {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/WebPushSettings
type WebPushSettings struct {
	Subject    string `json:"subject"`
	PublicKey  string `json:"public_key"`
	PrivateKey string `json:"private_key"`
}

// GetSubject returns the value of Subject.
func (s *WebPushSettings) GetSubject() string {
	return s.Subject
}

// GetPublicKey returns the value of PublicKey.
func (s *WebPushSettings) GetPublicKey() string {
	return s.PublicKey
}

// GetPrivateKey returns the value of PrivateKey.
func (s *WebPushSettings) GetPrivateKey() string {
	return s.PrivateKey
}

// SetSubject sets the value of Subject.
func (s *WebPushSettings) SetSubject(val string) {
	s.Subject = val
}

// SetPublicKey sets the value of PublicKey.
func (s *WebPushSettings) SetPublicKey(val string) {
	s.PublicKey = val
}

// SetPrivateKey sets the value of PrivateKey.
func (s *WebPushSettings) SetPrivateKey(val string) {
	s.PrivateKey = val
}

// Ref: #/components/schemas/WebPushTarget
type WebPushTarget struct {
	Endpoint url.URL `json:"endpoint"`
	P256dh   string  `json:"p256dh"`
	Auth     string  `json:"auth"`
}

// GetEndpoint returns the value of Endpoint.
func (s *WebPushTarget) GetEndpoint() url.URL {
	return s.Endpoint
}

// GetP256dh returns the value of P256dh.
func (s *WebPushTarget) GetP256dh() string {
	return s.P256dh
}

// GetAuth returns the value of Auth.
func (s *WebPushTarget) GetAuth() string {
	return s.Auth
}

// SetEndpoint sets the value of Endpoint.
func (s *WebPushTarget) SetEndpoint(val url.URL) {
	s.Endpoint = val
}

// SetP256dh sets the value of P256dh.
func (s *WebPushTarget) SetP256dh(val string) {
	s.P256dh = val
}

// SetAuth sets the value of Auth.
func (s *WebPushTarget) SetAuth(val string) {
	s.Auth = val
}
