// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleAdminSession handles AdminSession security.
	HandleAdminSession(ctx context.Context, operationName OperationName, t AdminSession) (context.Context, error)
	// HandleServiceKey handles ServiceKey security.
	HandleServiceKey(ctx context.Context, operationName OperationName, t ServiceKey) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesAdminSession is a private map storing roles per operation.
var operationRolesAdminSession = map[string][]string{
	IssueKeyOperation:        []string{},
	ListDeadLettersOperation: []string{},
	ListKeysOperation:        []string{},
	ListProjectsOperation:    []string{},
	ListProvidersOperation:   []string{},
	LogoutOperation:          []string{},
	PreviewOperation:         []string{},
	PutProjectOperation:      []string{},
	PutProviderOperation:     []string{},
	ReplayOperation:          []string{},
	RevokeKeyOperation:       []string{},
	TestSendOperation:        []string{},
}

// GetRolesForAdminSession returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForAdminSession(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForAdminSession(operation string) []string {
	roles, ok := operationRolesAdminSession[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesServiceKey is a private map storing roles per operation.
var operationRolesServiceKey = map[string][]string{
	GetPreferencesOperation: []string{},
	PutPreferencesOperation: []string{},
	SendOperation:           []string{},
}

// GetRolesForServiceKey returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForServiceKey(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForServiceKey(operation string) []string {
	roles, ok := operationRolesServiceKey[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityAdminSession(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t AdminSession
	const parameterName = "courier_session"
	var value string
	switch cookie, err := req.Cookie(parameterName); {
	case err == nil: // if NO error
		value = cookie.Value
	case errors.Is(err, http.ErrNoCookie):
		return ctx, false, nil
	default:
		return nil, false, errors.Wrap(err, "get cookie value")
	}
	t.APIKey = value
	t.Roles = operationRolesAdminSession[operationName]
	rctx, err := s.sec.HandleAdminSession(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityServiceKey(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ServiceKey
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesServiceKey[operationName]
	rctx, err := s.sec.HandleServiceKey(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// AdminSession provides AdminSession security value.
	AdminSession(ctx context.Context, operationName OperationName) (AdminSession, error)
	// ServiceKey provides ServiceKey security value.
	ServiceKey(ctx context.Context, operationName OperationName) (ServiceKey, error)
}

func (s *Client) securityAdminSession(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.AdminSession(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"AdminSession\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "courier_session",
		Value: t.APIKey,
	})
	return nil
}
func (s *Client) securityServiceKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ServiceKey(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ServiceKey\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
