// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetPreferences implements getPreferences operation.
//
// GET /v1/recipients/{recipient_id}/preferences
func (UnimplementedHandler) GetPreferences(ctx context.Context, params GetPreferencesParams) (r *Preferences, _ error) {
	return r, ht.ErrNotImplemented
}

// IssueKey implements issueKey operation.
//
// POST /admin/projects/{project_id}/keys
func (UnimplementedHandler) IssueKey(ctx context.Context, req *APIKeyRequest, params IssueKeyParams) (r *IssuedKey, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDeadLetters implements listDeadLetters operation.
//
// GET /admin/projects/{project_id}/dead-letters
func (UnimplementedHandler) ListDeadLetters(ctx context.Context, params ListDeadLettersParams) (r *DeadLetters, _ error) {
	return r, ht.ErrNotImplemented
}

// ListKeys implements listKeys operation.
//
// GET /admin/projects/{project_id}/keys
func (UnimplementedHandler) ListKeys(ctx context.Context, params ListKeysParams) (r *APIKeys, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProjects implements listProjects operation.
//
// GET /admin/projects
func (UnimplementedHandler) ListProjects(ctx context.Context) (r *Projects, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProviders implements listProviders operation.
//
// GET /admin/projects/{project_id}/providers
func (UnimplementedHandler) ListProviders(ctx context.Context, params ListProvidersParams) (r *Providers, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements login operation.
//
// POST /admin/session
func (UnimplementedHandler) Login(ctx context.Context, req *LoginRequest) error {
	return ht.ErrNotImplemented
}

// Logout implements logout operation.
//
// DELETE /admin/session
func (UnimplementedHandler) Logout(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// Preview implements preview operation.
//
// POST /admin/projects/{project_id}/preview
func (UnimplementedHandler) Preview(ctx context.Context, req *PreviewRequest, params PreviewParams) (r *Rendered, _ error) {
	return r, ht.ErrNotImplemented
}

// PutPreferences implements putPreferences operation.
//
// PUT /v1/recipients/{recipient_id}/preferences
func (UnimplementedHandler) PutPreferences(ctx context.Context, req *Preferences, params PutPreferencesParams) error {
	return ht.ErrNotImplemented
}

// PutProject implements putProject operation.
//
// PUT /admin/projects/{project_id}
func (UnimplementedHandler) PutProject(ctx context.Context, req *ProjectConfig, params PutProjectParams) error {
	return ht.ErrNotImplemented
}

// PutProvider implements putProvider operation.
//
// PUT /admin/projects/{project_id}/providers
func (UnimplementedHandler) PutProvider(ctx context.Context, req *ProviderSettings, params PutProviderParams) error {
	return ht.ErrNotImplemented
}

// Replay implements replay operation.
//
// POST /admin/projects/{project_id}/dead-letters/{delivery_id}/replay
func (UnimplementedHandler) Replay(ctx context.Context, params ReplayParams) error {
	return ht.ErrNotImplemented
}

// RevokeKey implements revokeKey operation.
//
// DELETE /admin/projects/{project_id}/keys/{key_id}
func (UnimplementedHandler) RevokeKey(ctx context.Context, params RevokeKeyParams) error {
	return ht.ErrNotImplemented
}

// Send implements send operation.
//
// POST /v1/messages
func (UnimplementedHandler) Send(ctx context.Context, req *SendRequest) (r *Accepted, _ error) {
	return r, ht.ErrNotImplemented
}

// TestSend implements testSend operation.
//
// POST /admin/projects/{project_id}/test
func (UnimplementedHandler) TestSend(ctx context.Context, req *SendRequest, params TestSendParams) (r *Accepted, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ProblemStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ProblemStatusCode) {
	r = new(ProblemStatusCode)
	return r
}
