// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetPreferencesOperation  OperationName = "GetPreferences"
	IssueKeyOperation        OperationName = "IssueKey"
	ListDeadLettersOperation OperationName = "ListDeadLetters"
	ListKeysOperation        OperationName = "ListKeys"
	ListProjectsOperation    OperationName = "ListProjects"
	ListProvidersOperation   OperationName = "ListProviders"
	LoginOperation           OperationName = "Login"
	LogoutOperation          OperationName = "Logout"
	PreviewOperation         OperationName = "Preview"
	PutPreferencesOperation  OperationName = "PutPreferences"
	PutProjectOperation      OperationName = "PutProject"
	PutProviderOperation     OperationName = "PutProvider"
	ReplayOperation          OperationName = "Replay"
	RevokeKeyOperation       OperationName = "RevokeKey"
	SendOperation            OperationName = "Send"
	TestSendOperation        OperationName = "TestSend"
)
