import { chromium } from 'playwright';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

const environment = Object.fromEntries((await readFile('.env','utf8')).split('\n').filter(line=>line.includes('=')).map(line=>{const index=line.indexOf('=');return [line.slice(0,index),line.slice(index+1)];}));
const browser = await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
const errors=[];
try {
 const page=await browser.newPage({viewport:{width:1440,height:1050}});
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto(environment.COURIER_PUBLIC_URL);
 const favicon=await page.locator('link[rel="icon"]').getAttribute('href');
 assert.equal(favicon,'/favicon.svg');
 const icon=await page.request.get(new URL(favicon,environment.COURIER_PUBLIC_URL).href);
 assert.equal(icon.status(),200);
 assert.match(icon.headers()['content-type'],/image\/svg\+xml/);
 await page.locator('.brand-mark').first().evaluate(image=>image.decode());
 await page.locator('#master-key').fill(environment.COURIER_ADMIN_KEY);
 await page.locator('#login-form button').click();
 await page.locator('#new-project').waitFor();
 await page.locator('#new-project').click();
 const project=`browser-${Date.now()}`;
 await page.locator('#project-id').fill(project);
 await page.locator('#project-ru').fill('Проверка доставки');
 await page.locator('#project-en').fill('Delivery verification');
 await page.locator('#create-project').click();
 await page.locator('#new-notification').waitFor();
 await page.locator('#new-notification').click();
 await page.locator('#new-key').fill('registration');
 await page.locator('#add-key').click();
 await page.locator('#title-ru').fill('Регистрация');
 await page.locator('#title-en').fill('Registration');
 await page.locator('[data-editor-tab="templates"]').click();
 await page.locator('#subject').fill('Добро пожаловать, {{.name}}');
 await page.locator('#text').fill('Courier доставляет сообщение для {{.name}}.');
 await page.locator('#html').fill('<h1>Привет, {{.name}}</h1>');
 await page.locator('[data-editor-tab="schema"]').click();
 await page.locator('#add-field').click();
 await page.locator('[data-name]').fill('name');
 await page.locator('[data-label-ru]').fill('Имя');
 await page.locator('[data-label-en]').fill('Name');
 await page.locator('#save-notification').click();
 await page.waitForFunction(()=>document.querySelector('#notice')?.textContent==='Изменения действуют.');
 await page.locator('[data-editor-tab="test"]').click();
 await page.locator('#sample-data').fill('{"name":"<Alex>"}');
 await page.locator('#preview').click();
 await page.locator('#html-preview').waitFor();
 assert.match(await page.locator('#preview-result h4').innerText(),/<Alex>/);
 assert.match(await page.locator('#html-preview').evaluate(frame=>frame.srcdoc),/&lt;Alex&gt;/);
 await page.locator('[data-editor-tab="templates"]').click();
 assert.equal(await page.locator('#subject').inputValue(),'Добро пожаловать, {{.name}}');
 await page.screenshot({path:'.build/admin-desktop.png',fullPage:true});
 await page.locator('[data-editor-tab="schema"]').click();
 assert.equal(await page.locator('[data-name]').inputValue(),'name');
 await page.screenshot({path:'.build/admin-schema.png',fullPage:true});
 await page.locator('[data-tab="providers"]').click();
 await page.locator('[data-provider="email"]').waitFor();
 await page.screenshot({path:'.build/admin-providers.png',fullPage:true});
 await page.locator('[data-provider="email"]').click();
 await page.locator('#smtp-host').fill('127.0.0.1');
 await page.locator('#smtp-port').fill('11025');
 await page.locator('#smtp-tls').selectOption('plain');
 await page.locator('#smtp-from').fill('courier@example.test');
 await page.locator('#save-provider').click();
 await page.locator('[data-provider="email"]').waitFor();
 await page.locator('[data-tab="notifications"]').click();
 await page.locator('[data-editor-tab="test"]').click();
 await page.locator('#sample-data').fill('{"name":"Browser"}');
 await page.locator('#test-target').fill('{"address":"browser@example.test"}');
 await page.locator('#test-send').click();
 await page.waitForFunction(()=>document.querySelector('#notice')?.textContent?.startsWith('Тест принят в очередь:'));
 await page.reload();
 await page.locator('#new-notification').waitFor();
 const picker=page.locator('#project-switcher');
 await picker.selectOption(project);
 await page.locator('[data-editor-tab="templates"]').click();
 assert.equal(await page.locator('#subject').inputValue(),'Добро пожаловать, {{.name}}');
 await page.locator('[data-tab="keys"]').click();
 await page.locator('#issue-key').waitFor();
 await page.screenshot({path:'.build/admin-access.png',fullPage:true});
 await page.locator('[data-tab="dead"]').click();
 await page.locator('#refresh-dead').waitFor();
 await page.screenshot({path:'.build/admin-dead.png',fullPage:true});
 await page.locator('[data-tab="project"]').click();
 await page.locator('#save-project').waitFor();
 assert.equal(await page.locator('#project-ru').inputValue(),'Проверка доставки');
 await page.locator('[data-tab="notifications"]').click();
 await page.locator('#language').click();
 assert.equal(await page.locator('h1').innerText(),'Delivery verification');
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'.build/admin-mobile.png',fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 assert.equal(overflow,false,'Admin UI overflows on mobile');
 for(const editor of ['general','schema','test']){
  await page.locator(`[data-editor-tab="${editor}"]`).click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`Mobile overflow in ${editor}`);
 }
 await page.locator('[data-tab="providers"]').click();
 await page.locator('[data-provider="email"]').waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile providers overflow');
 await page.locator('#logout').click();
 await page.locator('#master-key').waitFor();
 await page.screenshot({path:'.build/admin-login.png',fullPage:true});
 assert.deepEqual(errors,[],'Browser runtime errors');
 console.log('Browser flow passed: login, project, visual schema, localized templates, preview, SMTP setup, test send, language, mobile, logout.');
} finally {await browser.close();}
